{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a66bc3b-aba0-4fd2-bf0b-291e912a9396",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import cv2\n",
    "from skimage.feature import graycomatrix, graycoprops\n",
    "from PIL import Image\n",
    "import io\n",
    "\n",
    "st.set_page_config(layout=\"wide\")\n",
    "st.title(\"🌿 Aplikasi Pengolahan Citra Daun\")\n",
    "\n",
    "st.sidebar.header(\"📂 Upload Gambar\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Pilih file gambar (JPG/PNG)\", type=[\"jpg\", \"png\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    # Load gambar\n",
    "    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)\n",
    "    img = cv2.imdecode(file_bytes, 1)\n",
    "    img = cv2.resize(img, (300, 300))\n",
    "\n",
    "    # Preprocessing\n",
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    blur = cv2.GaussianBlur(gray, (5, 5), 0)\n",
    "\n",
    "    # Segmentasi\n",
    "    _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n",
    "\n",
    "    # Ekstraksi ciri\n",
    "    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "    cnt = max(contours, key=cv2.contourArea) if contours else None\n",
    "    luas = cv2.contourArea(cnt) if cnt is not None else 0\n",
    "    keliling = cv2.arcLength(cnt, True) if cnt is not None else 0\n",
    "\n",
    "    glcm = graycomatrix(gray, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)\n",
    "    kontras = graycoprops(glcm, 'contrast')[0, 0]\n",
    "    homogenitas = graycoprops(glcm, 'homogeneity')[0, 0]\n",
    "\n",
    "    mask = thresh == 255\n",
    "    rata_r = np.mean(img[:, :, 2][mask])\n",
    "    rata_g = np.mean(img[:, :, 1][mask])\n",
    "    rata_b = np.mean(img[:, :, 0][mask])\n",
    "\n",
    "    # Tampilkan gambar hasil\n",
    "    st.subheader(\"🖼️ Hasil Pengolahan Gambar\")\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    col1.image(cv2.cvtColor(img, cv2.COLOR_BGR2RGB), caption=\"Asli\", use_column_width=True)\n",
    "    col2.image(gray, caption=\"Grayscale\", use_column_width=True, channels=\"GRAY\")\n",
    "    col3.image(blur, caption=\"Blur\", use_column_width=True, channels=\"GRAY\")\n",
    "    col4.image(thresh, caption=\"Segmentasi\", use_column_width=True, channels=\"GRAY\")\n",
    "\n",
    "    # Tampilkan fitur\n",
    "    st.subheader(\"📊 Ekstraksi Fitur:\")\n",
    "    st.markdown(f\"\"\"\n",
    "    - **Luas:** {luas:.2f} piksel  \n",
    "    - **Keliling:** {keliling:.2f} piksel  \n",
    "    - **Tekstur Kontras:** {kontras:.4f}  \n",
    "    - **Tekstur Homogenitas:** {homogenitas:.4f}  \n",
    "    - **Rata-rata Warna R:** {rata_r:.2f}  \n",
    "    - **Rata-rata Warna G:** {rata_g:.2f}  \n",
    "    - **Rata-rata Warna B:** {rata_b:.2f}  \n",
    "    \"\"\")\n",
    "else:\n",
    "    st.info(\"📤 Silakan unggah gambar daun untuk mulai.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
